boot.o: boot.S multiboot.h x86_desc.h types.h
handler.o: handler.S
paging.o: paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h x86_desc.h devices/keyboard.h \
  devices/../types.h devices/../i8259.h devices/../types.h devices/RTC.h \
  handler.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h devices/keyboard.h devices/../types.h devices/../i8259.h idt.h \
  nPage.h devices/RTC.h
lib.o: lib.c lib.h types.h devices/keyboard.h devices/../types.h \
  devices/../i8259.h devices/../types.h
nPage.o: nPage.c nPage.h lib.h types.h x86_desc.h
terminal.o: terminal.c terminal.h types.h lib.h i8259.h \
  devices/keyboard.h devices/../types.h devices/../i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
keyboard.o: devices/keyboard.c devices/../lib.h devices/../types.h \
  devices/keyboard.h devices/../types.h devices/../i8259.h \
  devices/../terminal.h
RTC.o: devices/RTC.c devices/RTC.h devices/../types.h devices/../i8259.h \
  devices/../types.h devices/../lib.h
